### PR TITLE
Fix calcEstimation with last reward ( neword is not 16XMR close 13XMR No...

### PR DESCRIPTION
**Pull request by perl5577**
...w)

### CODE REVIEW

**Comment by zone117x** [comment]
@sammy007  Are you endorsing this change?

**Comment by sammy007** [comment]
Using `lastReward` is correct, I bet you have to adjust block time also since last fork, block time is 2 minutes.

**Comment by zone117x** [comment]
Thanks @sammy007 
Could you submit a pull for fixing block time

**Comment by sammy007** [comment]
I believe someone who is running pool already have these changes and can make high quality PR. I have no environment for patching/testing it ATM.

**Comment by zone117x** [comment]
Do you know who? What repo?

**Comment by sammy007** [comment]
I guess @Gingeropolous can.

**Pull request merged**
