### PR TITLE
Change address verification to a base58 match

### PR DESCRIPTION
**Pull request by Snipa22**
This is how I'm doing the address verification on my pool, ensures that the pool is compatible with addresses of an identical type.

### CODE REVIEW

**Comment by zone117x** [comment]
This seems like a good approach. "WIP" - is there further work you want to do before merging?

Thanks Snippa!

**Comment by Snipa22** [comment]
There's still a bug reported by Blob1235 upstream for testnet.  I need to pull a couple more address chunks out to test for good measure.

**Comment by Snipa22** [comment]
This has been checked and verified by myself at this time. I suspect that Blob1235 was using an invalid address.  This verifies non-integrated addresses correctly. Integrated addresses still break with this fix.

**Comment by zone117x** [comment]
Thanks a lot Snipa

**Pull request merged**
